# Generated by Django 2.0.7 on 2018-07-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=36)),
                ('trackid', models.CharField(max_length=20)),
                ('categoryid', models.CharField(max_length=25)),
                ('brandname', models.CharField(max_length=25)),
                ('img1', models.CharField(max_length=200)),
                ('childcid1', models.CharField(max_length=25)),
                ('productid1', models.CharField(max_length=25)),
                ('longname1', models.CharField(max_length=25)),
                ('price1', models.CharField(default=0, max_length=25)),
                ('marketprice1', models.CharField(default=0, max_length=25)),
                ('img2', models.CharField(max_length=200)),
                ('childcid2', models.CharField(max_length=25)),
                ('productid2', models.CharField(max_length=25)),
                ('longname2', models.CharField(max_length=25)),
                ('price2', models.CharField(default=0, max_length=25)),
                ('marketprice2', models.CharField(default=0, max_length=25)),
                ('img3', models.CharField(max_length=200)),
                ('childcid3', models.CharField(max_length=25)),
                ('productid3', models.CharField(max_length=25)),
                ('longname3', models.CharField(max_length=25)),
                ('price3', models.CharField(default=0, max_length=25)),
                ('marketprice3', models.CharField(default=0, max_length=25)),
            ],
            options={
                'db_table': 'axf_mainshow',
            },
        ),
    ]
