# Generated by Django 2.0.7 on 2018-07-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_mainshow'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.CharField(max_length=25)),
                ('typename', models.CharField(max_length=25)),
                ('childtypenames', models.CharField(max_length=25)),
                ('typesort', models.CharField(max_length=25)),
            ],
        ),
    ]
