# Generated by Django 2.0.7 on 2018-07-31 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_mainmarket'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mainmarket',
            table='axf_foodtypes',
        ),
    ]
