# Generated by Django 2.0.7 on 2018-07-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20180731_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=25)),
                ('productimg', models.CharField(max_length=100)),
                ('productname', models.CharField(max_length=25)),
                ('productlongname', models.CharField(max_length=25)),
                ('isxf', models.BooleanField(default=False)),
                ('pmdesc', models.IntegerField(default=0)),
                ('specifics', models.CharField(max_length=10)),
                ('price', models.FloatField(default=1)),
                ('marketprice', models.FloatField(default=1)),
                ('categoryid', models.IntegerField(default=0)),
                ('childcid', models.IntegerField(default=0)),
                ('childcidname', models.CharField(max_length=25)),
                ('dealerid', models.CharField(max_length=25)),
                ('storenums', models.IntegerField(default=0)),
                ('productnum', models.IntegerField(default=0)),
            ],
        ),
    ]
