# Generated by Django 2.0.7 on 2018-07-31 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_goods'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goods',
            table='axf_goods',
        ),
    ]
