# Generated by Django 2.0.7 on 2018-07-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_auto_20180731_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='productname',
            field=models.CharField(max_length=32),
        ),
    ]
