# Generated by Django 2.0.7 on 2018-07-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20180731_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='productname',
            field=models.CharField(max_length=100),
        ),
    ]
