# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-01 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_auto_20180731_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36, unique=True)),
                ('email', models.CharField(max_length=25, unique=True)),
                ('phone', models.CharField(max_length=18, unique=True)),
                ('pwd', models.CharField(max_length=200)),
                ('gender', models.BooleanField(default=False)),
                ('icon', models.ImageField(default=None, upload_to='icons')),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
